CSV_FILE = "filters.csv"
PATH = "test_files_filters"

PLOT_OPTIONS = {
    "alpha": 0.3,
    "backend": "svg",
    "by_name": False,
    "dry_run": False,
    "font": "times",
    "font_sz": 12.0,
    "no_grid": False,
    "grid_color": "black",
    "grid_style": ":",
    "grid_width": "1",
    "join_key": None,
    "key": "rtime",
    "legend": ["prog_alias"],
    "lgd_alpha": 1.0,
    "lgd_fancy": True,
    "lgd_shadow": True,
    "lgd_loc": "upper left",
    "lgd_ncol": 1,
    "only": None,
    "plot_type": "cactus",
    "repls": None,
    "reverse": False,
    "save_to": "examples/cactus.png",
    "shape": "standard",
    "timeout": None,
    "t_label": None,
    "tlb_loc": "after",
    "transparent": False,
    "usetex": True,
    "vbs": None,
    "xkcd": False,
    "x_label": None,
    "x_log": False,
    "x_min": 0,
    "x_max": None,
    "y_label": None,
    "y_log": False,
    "y_min": 1e-09,
    "y_max": None,
    "def_path": "../mkplot/defaults.json",
}
